



validation:

device_eval : "cuda"




documentation:

ablation_study_path :
ablation_study_title :






training:

compare : True
seed : 42
train_ratio : 0.7
val_ratio : 0.15
test_ratio : 0.15
split_dir : "/splitted_data/"
learning_rate : 0.001
batch_size : 64
num_workers : 8
device_train : "cuda"
model_architecture : 

data:

authorization : Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzM4MjYxNDksImV4cCI6MTc4OTM3ODE0OSwiYXVkIjoiYXV0aCIsInN1YiI6IkVpbmZhY2hudXJKdWxzIiwiaXNzIjoiaHR0cHM6Ly9kYXRseS5jb24uYnoifQ.MdzQE2syRt1Zgd_CXcpHOcWhuKjkCCzDZksQK1qYSvDxi7OYl9-0KBr2yBmHSbgEMXrq-pO9quoa3rtEwl9HVezxj2EuZdMo1E6j2wP1P129S-Q-0tJn6ABUU-s6V2s8skAtedxEVaLeO66UjygcUSk61QR8pFLtyibBw0Dx0m0w3zwi5tqHFUMQU0TEa0ozGoK1nv7J5f-99yLJ8sDIiRdPMqxNwUyiNWzpj5TOqsQyZI0m5AOao4iTe12x4RkXSYOxmM00wkm4vfJAbw-3ZjqyiVBU_G3Mr1XfhYi6lgksvdTT41digoW1s8ZSZahhJ3gI9UTBUKs0eLfddHO7rQ"
request_key : 
temp_dir : "/data_large_classifying/"
input_size : (224*224)

