



validation:

device_eval : "cpu"
val_model_architecture : "ResNet50.DEFAULT"
weights_path : "trained_models_large/model_transfer_presentation_ready.pth"



documentation:

ablation_study_path :
ablation_study_title :






training:

min_improve : 1e-3
patience : 7
compare : False
seed : 42
num_epochs : 50
train_ratio : 0.7
val_ratio : 0.15
test_ratio : 0.15
split_dir : "/splitted_data/"
batch_size : 32
num_workers : 8
device_train : "cuda"
model_architecture : "ResNet50.DEFAULT"

data:
raw_data_dir : "/data_large_classifying_raw/"
input_size : (224*224)

